Repaso definicion de api
UnirCs/DWFS-PER7610-2223 pull request #143
Opened 2023-02-26 03:44 UTC by LESLYCADENA96

Se realizo la tarea 1 del tema 6 y se hicieron los cambios sugeridos en las tareas del Tema 3

2023-02-28 23:25 UTC, UnirDwfs commented on Tema_6/lesly_cadena/T6_E2.md
> +
Está vacío

2023-02-28 23:26 UTC, UnirDwfs commented on Tema_6/lesly_cadena/T6_E1.md
> +|POST|	/usuarios|	{Id:1,Nombre: Juan,Apellido:Ortega,Email:juanortega@hotmail.com,Contrasena:  1256}|	201 OK 404 NF|Crear un usuario|
Tambien puede devolver 400

2023-02-28 23:26 UTC, UnirDwfs commented on Tema_6/lesly_cadena/T6_E1.md
> +|POST	/partida/{id_partida}/jugadores/{id_jugador}/ cuadriculas/{id_cuadricula}/disparos|	{Jugador_origen:Juan;Jugador_destino: Marco Numero_disparos_realizados:2,cuadricula_destino: {id_cuadricula}}
puede devolver 400

2023-02-28 23:26 UTC, UnirDwfs commented on Tema_6/lesly_cadena/T6_E1.md
> +|POST	|/partida/{id_partida}/jugadores/{id_jugador}/cuadriculas/{id_cuadricula}/barcos| {Nombre_barco:’selva_negra’,Posición_barco:[2,4]tamano:3 Sentido: horizontal}|	201 OK 404 NF	|Añadir un barco a
puede devolver 400

2023-02-28 23:27 UTC, UnirDwfs commented on Tema_6/lesly_cadena/T6_E1.md
> +
Algunas operaciones sobre la partida como añadir barcos pueden ser consideradas tambien PATCH

2023-02-28 23:28 UTC, UnirDwfs requested changes
Los archivos package.json y package-lock.json deben ser eliminados

2023-08-27 19:52 UTC, UnirCs commented
Se cierra PR por inactividad

2023-08-27 19:52 UTC, closed without merging