Ejercicio de repaso - examen
UnirCs/DWFS-PER7610-2223 pull request #146
Opened 2023-03-02 04:58 UTC by MariBedoya

Buen día profe, 
Sé que aun me falta algunas funcionalidades en el ms de catalogo, pero quería subir lo que llevo para ir recibiendo su feedback, creé el ms de eureka, zuul, catalogo y operador, y el front.

2023-03-02 22:41 UTC, UnirDwfs commented on EjercicioRepaso/MariluzBedoyaVasquez/back-catalogo/src/main/java/com/example/catalogo/entities/ElasticPizza.java
> +    @Field( type = FieldType.Integer, name="precio")
Es más logico definir esto como un Double, o Number

2023-03-02 22:44 UTC, UnirDwfs commented on EjercicioRepaso/MariluzBedoyaVasquez/back-operador/src/main/java/com/example/operador/controllers/PizzaController.java
> +    public ResponseEntity<List<PizzaEntity>> getAll() {
No tiene sentido este endpoint porque tienes el mismo en el ms de catalogo

2023-03-02 22:45 UTC, UnirDwfs commented on EjercicioRepaso/MariluzBedoyaVasquez/back-operador/src/main/java/com/example/operador/services/PedidoServiceImpl.java
> +    private String url_zuul;
Esto no es la url de zuul, sino la url del microservicio catalogo

2023-03-02 22:46 UTC, UnirDwfs commented on EjercicioRepaso/MariluzBedoyaVasquez/back-operador/src/main/resources/application.properties
> +url.zuul.busquedas=http://localhost:8085
deberia apuntar contra el ms catalogo, sin ip ni puerto

2023-03-02 22:46 UTC, UnirDwfs commented on EjercicioRepaso/MariluzBedoyaVasquez/front-pizzeria/src/components/Home.js
> +        fetch("http://localhost:8080/pizzas")
la peticion debe ir contra zuul, no contra un ms concreto

2023-03-02 22:47 UTC, UnirDwfs requested changes
Revisa los comentarios a nivel de diseño de api y de implementacion.
usa la solucion como referencia

2023-08-27 19:53 UTC, UnirCs commented
Se cierra PR por inactividad

2023-08-27 19:53 UTC, closed without merging